### ISSUE TITLE
error in main.py 

### ISSUE THREAD

**Issue by MR-pentestGuy** [MrCl0wnLab/ShellShockHunter#1]
when i ran python main.py --help 

File "main.py", line 34
    def grep_uid(_html:str):
                      ^
SyntaxError: invalid syntax

**Comment by MrCl0wnLab** [comment]
Hi @MR-pentestGuy ,
Which version of python did you use? 

I recommend using: Python 3.9.1

**Comment by MrCl0wnLab** [comment]
Issue closed due to lack of communication.
